### ISSUE TITLE
Invalid license tag

### ISSUE THREAD

**Issue by peti** [jotrk/xhb-atom-cache#1]
Citing from http://hydra.cryp.to/build/599345/log/raw:

> Warning: 'license: BSD2' is not a recognised license. The known licenses are: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD3, MIT, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense

**Comment by jchnkl** [comment]
Hm, I guess then `cabal init` shouldn't be offering `BSD2` as a choice. Otoh, `BSD2` is a [valid license](http://opensource.org/licenses/BSD-2-Clause) and it should be added to Hydra?

**Comment by peti** [comment]
It appears that the `BSD2` license is a new addition in Cabal 1.22.x: http://hackage.haskell.org/package/Cabal-1.22.1.1/docs/Distribution-License.html. Unfortunately, ghc 7.8.4 doesn't have that version yet, hence the warning. I guess there's not much one can do about that. :frowning:

**Comment by jchnkl** [comment]
Alright, then I'll leave it as is and wait for GHC to catch up. Thanks for reporting!
